name: Cross build

on: [ push, pull_request, workflow_dispatch]

env:
  GO_VERSION: "1.24"
  GOOS: windows

jobs:
  build:
    name: cross build smoke test
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v5

      - name: Set up Go 1.x
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Build dependencies
        run: |
          go get -v -t -d ./...
          make deps

      - name: Build wal-g for SQL Server
        run: |
          make sqlserver_build